pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 101-terraform-job/

variables:
- group: terraform-secrets

jobs:

- template: terraform-job-template.yml
  parameters:
    environment: test
    # Pass variables as environment variables.
    # Terraform recognizes TF_VAR prefixed environment variables.
    TerraformEnvVariables:
      TF_VAR_department: engineering
