pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/

stages:
- template: terraform-stages-template.yml
  parameters:
    environment: Staging
    TerraformVariables: -var environment=stage

- template: terraform-stages-template.yml
  parameters:
    environment: QA
    TerraformVariables: -var environment=qa
