pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/

stages:
- template: terraform-stages-template.yml
  parameters:
    environment: stage
    displayName: Staging
    TerraformVariables: -var department=Engineering

- template: terraform-stages-template.yml
  parameters:
    environment: qa
    displayName: QA
    TerraformVariables: -var department=QA
