pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/

variables:
  TerraformVersion: 0.12.17
  TerraformVariables: -var environment=stage
  TerraformBackendServiceConnection: Terraform
  TerraformEnvironmentServiceConnection: Terraform
  TerraformBackendResourceGroup: terraform
  TerraformBackendStorageAccount: terraformstarter
  TerraformBackendStorageContainer: terraformstate
  TerraformBackendStorageBlob: tf/terraform.tfstate


stages:
- template: terraform-stages-template.yml
  parameters:
    environment: Staging
    TerraformVariables: -var environment=stage

- template: terraform-stages-template.yml
  parameters:
    environment: QA
    TerraformVariables: -var environment=qa
