steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: ${{ parameters.TerraformVersion }}

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: Terraform init
  inputs:
    workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/terraform
    backendServiceArm: ${{ parameters.TerraformBackendServiceConnection }}
    backendAzureRmResourceGroupName: ${{ parameters.TerraformBackendResourceGroup }}
    backendAzureRmStorageAccountName: ${{ parameters.TerraformBackendStorageAccount }}
    backendAzureRmContainerName: ${{ parameters.TerraformBackendStorageContainer }}
    backendAzureRmKey: ${{ parameters.environment }}.tfstate

- task: AzureCLI@1
  displayName: Get ARM credentials for Terraform
  inputs:
    azureSubscription: ${{ parameters.TerraformEnvironmentServiceConnection }}
    scriptLocation: inlineScript
    inlineScript: |
      set -eu
      subscriptionId=$(az account show --query id -o tsv)
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
    addSpnToEnvironment: true
